export const pages = [
  { path: '/', title: 'Rubli | Serviços mais perto de você', description: 'Conheça o Rubli: uma forma de aproximar quem precisa de um serviço dos profissionais da sua região.', kind: 'home' },
  { path: '/como-funciona/', title: 'Como funciona | Rubli', description: 'Entenda a jornada de clientes e profissionais no Rubli.', kind: 'how' },
  { path: '/para-clientes/', title: 'Para clientes | Rubli', description: 'Conheça uma forma mais clara de encontrar e conversar com profissionais próximos.', kind: 'clients' },
  { path: '/para-profissionais/', title: 'Para profissionais | Rubli', description: 'Saiba como o Rubli aproxima profissionais de oportunidades na região.', kind: 'professionals' },
  { path: '/seguranca/', title: 'Confiança e segurança | Rubli', description: 'Informação, conversa e controle para fazer escolhas com mais tranquilidade.', kind: 'security' },
  { path: '/sobre/', title: 'Sobre o Rubli', description: 'A missão do Rubli é aproximar pessoas e profissionais para resolver necessidades do dia a dia.', kind: 'about' },
  { path: '/faq/', title: 'Perguntas frequentes | Rubli', description: 'Respostas sobre o Rubli, seus profissionais e a experiência de contratação.', kind: 'faq' },
  { path: '/contato/', title: 'Contato | Rubli', description: 'Encontre o canal oficial para falar com a equipe Rubli.', kind: 'contact' },
  { path: '/privacidade/', title: 'Privacidade | Rubli', description: 'Informações sobre a política de privacidade do Rubli.', kind: 'privacy' },
  { path: '/termos/', title: 'Termos de uso | Rubli', description: 'Informações sobre os termos de uso do Rubli.', kind: 'terms' }
];

const icon = (name) => ({
  pin: '<path d="M12 21s7-6.2 7-12a7 7 0 1 0-14 0c0 5.8 7 12 7 12Z"/><circle cx="12" cy="9" r="2.5"/>',
  chat: '<path d="M20 11.5a7.5 7.5 0 0 1-7.5 7.5H5l1.7-3.4A7.5 7.5 0 1 1 20 11.5Z"/><path d="M9 10h7M9 13h5"/>',
  shield: '<path d="m12 2 8 4v5c0 5-3.3 8.5-8 11-4.7-2.5-8-6-8-11V6l8-4Z"/><path d="m9 12 2 2 4-4"/>',
  spark: '<path d="m12 2 2.2 7.8L22 12l-7.8 2.2L12 22l-2.2-7.8L2 12l7.8-2.2L12 2Z"/>',
  user: '<circle cx="12" cy="8" r="4"/><path d="M4 21a8 8 0 0 1 16 0"/>',
  check: '<path d="m5 12 4 4L19 6"/>'
})[name];
const svg = (name) => `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${icon(name)}</svg>`;
const link = (href, label, className = 'button button-primary') => `<a class="${className}" href="${href}">${label}<span aria-hidden="true">↗</span></a>`;
const eyebrow = (text) => `<p class="eyebrow">${text}</p>`;
const section = (label, title, copy, inner, extra = '') => `<section class="section ${extra}"><div class="container">${eyebrow(label)}<div class="section-heading"><h2>${title}</h2><p>${copy}</p></div>${inner}</div></section>`;
const card = (glyph, title, copy, extra = '') => `<article class="card ${extra}"><span class="icon-box">${svg(glyph)}</span><h3>${title}</h3><p>${copy}</p></article>`;
const grid = (items, className = 'grid-four') => `<div class="${className}">${items.join('')}</div>`;
const cta = (title = 'Precisou. Encontrou. Resolveu.') => `<section class="cta-band"><div class="container cta-inner"><div>${eyebrow('O próximo passo')}<h2>${title}</h2><p>Conheça a proposta do Rubli e descubra como ele aproxima pessoas e profissionais.</p></div><div class="cta-actions">${link('/para-clientes/', 'Quero contratar')}${link('/para-profissionais/', 'Sou profissional', 'button button-light')}</div></div></section>`;
const pageHero = (label, title, copy) => `<section class="page-hero"><div class="container">${eyebrow(label)}<h1>${title}</h1><p>${copy}</p></div></section>`;

const steps = [
  ['01', 'Conte o que precisa', 'Descreva o serviço com as informações necessárias.'],
  ['02', 'Conheça as opções', 'Veja perfis e propostas disponíveis para avaliar a melhor escolha.'],
  ['03', 'Converse e combine', 'Alinhe detalhes, valores e expectativas antes de decidir.'],
  ['04', 'Siga até a conclusão', 'Acompanhe o combinado e compartilhe sua experiência.']
];
const stepGrid = () => `<div class="steps">${steps.map(([number, title, copy]) => `<article class="step"><span>${number}</span><h3>${title}</h3><p>${copy}</p></article>`).join('')}</div>`;
const faqItems = [
  ['O que é o Rubli?', 'O Rubli é um marketplace digital pensado para aproximar pessoas que precisam de serviços de profissionais da região.'],
  ['Como encontro um profissional?', 'A experiência proposta começa com a descrição da sua necessidade. As etapas e opções disponíveis podem variar conforme a versão do aplicativo e a região.'],
  ['Posso conversar antes de contratar?', 'A negociação é parte da jornada proposta pelo Rubli. Confirme os recursos disponíveis na versão atual do aplicativo antes de tomar uma decisão.'],
  ['Como avalio um profissional?', 'O Rubli foi concebido para tornar perfis e experiências anteriores mais claros. A disponibilidade de avaliações depende da versão do produto.'],
  ['O Rubli verifica antecedentes criminais?', 'Não anunciamos checagem de antecedentes criminais. Consulte os canais oficiais para conhecer os procedimentos de cadastro e verificação vigentes.'],
  ['Quando meu endereço é compartilhado?', 'A forma de compartilhamento de localização depende das regras da versão do aplicativo. Antes de confirmar um serviço, confira as informações exibidas no próprio produto.'],
  ['Como entro em contato com o suporte?', 'Acesse a página de contato para consultar o canal oficial, quando estiver publicado.']
];
const faqList = (limit = faqItems.length) => `<div class="faq-list">${faqItems.slice(0, limit).map(([q, a]) => `<details><summary>${q}<span aria-hidden="true">+</span></summary><p>${a}</p></details>`).join('')}</div>`;

export function renderPage(kind, config) {
  switch (kind) {
    case 'home': return `
      <section class="hero"><div class="container hero-grid"><div class="hero-copy">${eyebrow('Serviços mais perto de você')}<h1>Encontre quem <em>resolve.</em><br>Com mais clareza e confiança.</h1><p>O Rubli aproxima você de profissionais da região para conversar, comparar opções e escolher com tranquilidade.</p><div class="hero-actions">${link('/para-clientes/', 'Encontre um profissional')}${link('/para-profissionais/', 'Quero trabalhar', 'button button-outline')}</div><div class="hero-note">${svg('shield')} Informação para escolher com mais segurança</div></div><div class="hero-visual" aria-label="Ilustração conceitual da experiência Rubli"><div class="glow"></div><div class="floating-card floating-top"><span class="mini-icon">${svg('pin')}</span><div><strong>Por perto</strong><small>Profissionais da sua região</small></div></div><div class="phone"><div class="phone-notch"></div><div class="phone-top"><span>rubli</span><span>◉</span></div><p class="phone-label">O que você precisa?</p><div class="phone-search">Buscar um serviço <span>⌕</span></div><div class="phone-list"><div class="phone-avatar">R</div><div><strong>Encontre opções</strong><small>Compare e converse</small></div><span>›</span></div><div class="phone-list"><div class="phone-avatar orange">✓</div><div><strong>Escolha com calma</strong><small>Decida no seu tempo</small></div><span>›</span></div><div class="phone-bottom"></div></div><div class="floating-card floating-bottom"><span class="mini-icon orange-icon">${svg('chat')}</span><div><strong>Conversa clara</strong><small>Combine os detalhes</small></div></div><span class="visual-caption">Ilustração da proposta do produto</span></div></div></section>
      ${section('Uma jornada mais simples', 'Do problema à solução, em um só lugar.', 'O Rubli reúne as etapas essenciais para você tomar uma decisão informada.', grid([card('spark', 'Conte o que precisa', 'Explique a necessidade de forma clara.'), card('pin', 'Explore opções', 'Conheça profissionais próximos.'), card('chat', 'Converse', 'Tire dúvidas e alinhe expectativas.'), card('check', 'Escolha', 'Decida o que faz sentido para você.')]))}
      ${section('Como funciona', 'Você no controle de cada etapa.', 'Da primeira conversa até o serviço concluído, uma experiência pensada para ser simples.', stepGrid(), 'section-soft')}
      ${section('Confiança', 'Boas escolhas começam com informação.', 'Conhecer o profissional, entender a proposta e combinar os detalhes ajuda a contratar com mais tranquilidade.', `<div class="feature-split"><div class="trust-panel"><span class="trust-symbol">${svg('shield')}</span><h3>Mais clareza para decidir.</h3><p>O que importa deve ser fácil de encontrar: informações do profissional, contexto do serviço e espaço para conversar.</p></div>${grid([card('user', 'Perfis', 'Conheça as informações disponíveis sobre cada profissional.'), card('chat', 'Negociação', 'Converse sobre escopo e condições antes de decidir.'), card('shield', 'Privacidade', 'Considere com cuidado os dados que compartilha.'), card('check', 'Acompanhamento', 'Tenha clareza sobre as etapas do serviço.')], 'trust-grid')}</div><div class="section-link"><a href="/seguranca/">Conheça nossa abordagem de confiança <span aria-hidden="true">→</span></a></div>`)}
      ${section('Para cada necessidade', 'Pessoas e profissionais, mais próximos.', 'Uma proposta para conectar demanda e trabalho no dia a dia.', `<div class="audience-grid"><article class="audience-card"><span>01 / Para clientes</span><h3>Precisou? Encontre quem pode resolver.</h3><p>Conheça opções, compare informações e converse antes de escolher.</p><a href="/para-clientes/">Conhecer a jornada <span aria-hidden="true">→</span></a></article><article class="audience-card audience-dark"><span>02 / Para profissionais</span><h3>Mais oportunidades perto de você.</h3><p>Apresente seu trabalho e conheça uma nova forma de se conectar à sua região.</p><a href="/para-profissionais/">Saiba mais <span aria-hidden="true">→</span></a></article></div>`)}
      ${section('ClubeOn', 'Sua festa começa com uma boa escolha.', 'Encontre clubes, chácaras, espaços de eventos e fornecedores para sua festa no catálogo ClubeOn.', `<div class="contact-card"><h3>Espaços e serviços para festas</h3><p>Consulte fotos, estrutura e informações dos anúncios. Quem oferece um espaço ou serviço também pode publicar gratuitamente.</p>${link('https://clubeon.rubli.com.br/', 'Explorar o catálogo')}</div>`)}
      ${section('Perguntas frequentes', 'Dúvidas comuns, respostas diretas.', 'Conheça melhor a proposta do Rubli.', `${faqList(4)}<div class="section-link"><a href="/faq/">Ver todas as perguntas <span aria-hidden="true">→</span></a></div>`, 'section-soft')}${cta()}`;
    case 'how': return `${pageHero('Como funciona', 'Uma jornada clara do começo ao fim.', 'O Rubli foi pensado para facilitar o encontro entre quem precisa de ajuda e quem sabe resolver.')}${section('Para quem precisa contratar', 'Da necessidade à escolha.', 'As etapas abaixo apresentam a experiência proposta pelo Rubli. Recursos concretos dependem da versão do aplicativo.', stepGrid())}${section('Para quem quer trabalhar', 'Seu trabalho pode encontrar novas oportunidades.', 'Apresente sua atuação, conheça demandas da região e converse sobre cada serviço.', grid([card('user', 'Apresente-se', 'Mostre sua área de atuação e experiência.'), card('pin', 'Atue por região', 'Encontre oportunidades compatíveis com sua localidade.'), card('chat', 'Converse', 'Entenda a necessidade e alinhe uma proposta.'), card('spark', 'Construa reputação', 'Faça um bom trabalho e fortaleça sua trajetória.')]), 'section-soft')}${cta('Perto de quem precisa. Perto de quem resolve.')}`;
    case 'clients': return `${pageHero('Para clientes', 'Resolver um problema não precisa virar outro.', 'Conheça uma experiência feita para ajudar você a encontrar opções, conversar e escolher com mais clareza.')}${section('Sua jornada', 'Você continua no controle.', 'Informação e conversa ajudam a transformar uma necessidade em uma decisão bem pensada.', grid([card('pin', 'Encontre por perto', 'Busque soluções relevantes para a sua região.'), card('user', 'Conheça melhor', 'Observe as informações disponíveis no perfil.'), card('chat', 'Combine os detalhes', 'Converse sobre prazo, escopo e valor.'), card('check', 'Decida com calma', 'Compare possibilidades antes de confirmar.')]))}${cta('Encontre quem pode ajudar.')}`;
    case 'professionals': return `${pageHero('Para profissionais', 'Seu trabalho merece ser encontrado.', 'O Rubli quer aproximar profissionais de pessoas que precisam resolver demandas reais na região.')}${section('Seu caminho', 'Mais visibilidade para o que você faz.', 'Apresente sua atuação e construa uma relação clara com potenciais clientes.', grid([card('user', 'Mostre seu trabalho', 'Explique seus serviços e especialidades.'), card('pin', 'Defina sua atuação', 'Organize a região em que deseja atender.'), card('chat', 'Envie propostas', 'Converse sobre a demanda e as condições.'), card('spark', 'Cuide da reputação', 'Cada experiência ajuda a construir confiança.')]))}${section('Possibilidades', 'Serviços para diferentes necessidades.', 'A disponibilidade de cada modalidade será comunicada nos canais oficiais do produto.', `<div class="category-grid"><div><span>01</span><h3>Serviços</h3><p>Reparos, manutenção, limpeza e outros trabalhos especializados.</p></div><div><span>02</span><h3>Entregas</h3><p>Uma modalidade prevista para demandas de retirada e deslocamento.</p></div><div><span>03</span><h3>Fretes</h3><p>Uma modalidade prevista para transporte e mudanças.</p></div></div>`, 'section-soft')}${cta('Seu próximo cliente pode estar por perto.')}`;
    case 'security': return `${pageHero('Confiança e segurança', 'Confiança se constrói com informação e controle.', 'Antes de contratar, vale entender quem vai realizar o serviço, o que foi combinado e quais dados você está compartilhando.')}${section('Escolha informada', 'Mais clareza em cada decisão.', 'A experiência do Rubli é orientada por transparência e autonomia.', grid([card('user', 'Conheça o perfil', 'Observe as informações apresentadas pelo profissional.'), card('chat', 'Converse antes', 'Esclareça o serviço, o prazo e as condições.'), card('shield', 'Cuide da privacidade', 'Compartilhe dados pessoais apenas quando necessário.'), card('check', 'Confira o combinado', 'Revise os detalhes antes de confirmar.')]))}<section class="notice-section"><div class="container"><div class="notice"><h2>Sobre verificações e garantias</h2><p>Procedimentos de cadastro e verificação podem mudar. O Rubli não promete segurança absoluta nem anuncia checagem de antecedentes criminais nesta página. Consulte as informações exibidas no aplicativo e os canais oficiais antes de contratar.</p></div></div></section>${cta('Escolha com mais informação.')}`;
    case 'about': return `${pageHero('Sobre o Rubli', 'Aproximar pessoas é o primeiro passo para resolver.', 'O Rubli nasce da ideia de tornar mais simples a conexão entre quem precisa de um serviço e quem pode realizá-lo.')}${section('Nossa direção', 'Serviços mais perto de você.', 'Queremos que a experiência de encontrar ajuda seja mais clara, humana e próxima.', `<div class="feature-split"><div class="trust-panel"><span class="trust-symbol">${svg('pin')}</span><h3>Proximidade que faz sentido.</h3><p>Conectar necessidades reais a trabalho local, com espaço para informação, conversa e boas escolhas.</p></div>${grid([card('shield', 'Confiança', 'Decisões melhores começam com transparência.'), card('chat', 'Simplicidade', 'Uma jornada fácil de entender.'), card('user', 'Respeito', 'Pessoas dos dois lados da experiência.'), card('spark', 'Evolução', 'Melhorias guiadas pelo que importa aos usuários.')], 'trust-grid')}</div>`)}${cta()}`;
    case 'faq': return `${pageHero('Perguntas frequentes', 'O que você quer saber sobre o Rubli?', 'Reunimos respostas sobre a proposta do produto. Para detalhes operacionais, consulte sempre a versão atual do aplicativo.')}${section('Respostas', 'Informação para começar.', 'Se sua dúvida não estiver aqui, procure nossos canais oficiais.', faqList())}${cta()}`;
    case 'contact': return `${pageHero('Contato', 'Vamos conversar.', 'Use os canais oficiais do Rubli para tirar dúvidas, relatar um problema ou enviar uma sugestão.')}<section class="section"><div class="container contact-layout"><div><h2>Escolha o canal certo.</h2><p>Fale com nossa equipe para conhecer os produtos, tirar dúvidas ou solicitar suporte. Não pedimos senhas nem códigos de acesso pelo atendimento.</p></div><div class="contact-card"><span class="icon-box">${svg('chat')}</span><h3>Atendimento Rubli</h3><p>${config.supportUrl ? 'Acesse o canal oficial de atendimento.' : 'O canal oficial de atendimento será publicado aqui em breve.'}</p>${config.supportUrl ? link(config.supportUrl, 'Falar com a equipe') : '<span class="status-pill">Canal em preparação</span>'}</div></div></section>`;
    case 'privacy': return legal('Política de privacidade', config.legalDocs.privacy);
    case 'terms': return legal('Termos de uso', config.legalDocs.terms);
    default: throw new Error(`Unknown page: ${kind}`);
  }
}

function legal(title, document) {
  return `${pageHero('Informações legais', title, 'Consulte abaixo o documento do Rubli e sua data de versão.')}<section class="section legal-section"><div class="container legal-layout"><nav class="legal-toc" aria-label="Nesta página"><span>Nesta página</span>${document.headings.map(heading => `<a href="#${heading.id}">${heading.text}</a>`).join('')}</nav><article class="legal-document">${document.html}</article></div></section>`;
}
